### ISSUE TITLE
Relicense

### ISSUE THREAD

**Issue by Emerentius** [Emerentius/sudoku#1]
As discussed in aochagavia/sudoku#7, this fork is moving to the AGPLv3.

#aochagavia, please answer within this thread that you're ok with that so it's attached to this repo.

**Comment by aochagavia** [comment]
I am ok with this!

**Comment by aochagavia** [comment]
By the way, I tried to remove myself as owner of the crate, but that is not allowed, so you will have to do that yourself (`cargo owner --remove aochagavia` should do it I think)
